enum ProductType {
  newProduct,
  secondHand,
  // onRent,
}

enum ProductQuantity { units, wkg, w500g, w250g, ltr, mtr, acre, feet }

var nameForProductQuantity = {
  ProductQuantity.units: "Units",
  ProductQuantity.wkg: "Kg",
  ProductQuantity.w500g: "500g",
  ProductQuantity.w250g: "250g",
  ProductQuantity.ltr: "Ltr",
  ProductQuantity.mtr: "Mtr",
  ProductQuantity.acre: "Acre",
  ProductQuantity.feet: "Feet",
};

enum ParentEnum {
  animal,
  food,
  machine,
  market,
}

var nameForParentEnum = {
  ParentEnum.animal: "Animals",
  ParentEnum.food: "Food",
  ParentEnum.machine: "Machine",
  ParentEnum.market: "Market",
};

var categoryListForParentEnum = {
  ParentEnum.animal: [
    CategoryEnum.animals,
    CategoryEnum.birds,
    CategoryEnum.supplies,
  ],
  ParentEnum.food: [
    CategoryEnum.vegetables,
    CategoryEnum.fruits,
    CategoryEnum.crops,
  ],
  ParentEnum.machine: [
    CategoryEnum.vehicles,
    CategoryEnum.equipments,
    CategoryEnum.tools,
  ],
  ParentEnum.market: [
    CategoryEnum.property,
    CategoryEnum.toysGadgets,
    CategoryEnum.houseItems,
    CategoryEnum.others,
    // CategoryEnum.vehicles,
    // CategoryEnum.landProperty,
    // CategoryEnum.toysGadget,
    // CategoryEnum.houseItems,
    // CategoryEnum.other,
  ],
};

var subCategoryListsForCategory = {
  CategoryEnum.animals: [
    SubCategoryEnum.cows,
    SubCategoryEnum.goats,
    SubCategoryEnum.buffaloes,
    SubCategoryEnum.sheep,
    SubCategoryEnum.bull,
    SubCategoryEnum.pig,
  ],
  CategoryEnum.birds: [
    SubCategoryEnum.parrot,
    SubCategoryEnum.pigeon,
    SubCategoryEnum.sparrow,
    SubCategoryEnum.duck,
    SubCategoryEnum.turkey,
    SubCategoryEnum.emu,
  ],
  CategoryEnum.supplies: [
    SubCategoryEnum.soaps,
    SubCategoryEnum.petShelters,
    SubCategoryEnum.transporters,
    SubCategoryEnum.cleaner,
    SubCategoryEnum.honeyTools,
    SubCategoryEnum.hive,
  ],
  CategoryEnum.vegetables: [
    SubCategoryEnum.beans,
    SubCategoryEnum.beetroot,
    SubCategoryEnum.bittergourd,
    SubCategoryEnum.bottlegourd,
    SubCategoryEnum.brinjal,
    SubCategoryEnum.brocolli,
  ],
  CategoryEnum.fruits: [
    SubCategoryEnum.banana,
    SubCategoryEnum.gauva,
    SubCategoryEnum.grapes,
    SubCategoryEnum.jackfruit,
    SubCategoryEnum.mango,
    SubCategoryEnum.muskmelon,
  ],
  CategoryEnum.crops: [
    SubCategoryEnum.barley,
    SubCategoryEnum.bengalGram,
    SubCategoryEnum.castor,
    SubCategoryEnum.cotton,
    SubCategoryEnum.groundnut,
    SubCategoryEnum.jute,
  ],
  CategoryEnum.equipments: [
    SubCategoryEnum.mobile,
    SubCategoryEnum.laptop,
    SubCategoryEnum.tv,
  ],
  CategoryEnum.vehicles: [
    SubCategoryEnum.jcb,
    SubCategoryEnum.tractor,
    SubCategoryEnum.rotavator,
    SubCategoryEnum.cultivator,
    SubCategoryEnum.Loader,
    SubCategoryEnum.Backhoe,
  ],
  CategoryEnum.tools: [
    SubCategoryEnum.ElectricScooter,
    SubCategoryEnum.Equipment,
    SubCategoryEnum.Scooter,
    SubCategoryEnum.Fan,
    SubCategoryEnum.GardeningTools,
    SubCategoryEnum.Plow,
  ],
  CategoryEnum.property: [
    SubCategoryEnum.rentalProperty,
    SubCategoryEnum.farmStay,
    SubCategoryEnum.farmRental,
    SubCategoryEnum.buyNsale,
    SubCategoryEnum.farmLabour,
    SubCategoryEnum.greenhouse,
    SubCategoryEnum.otherProperty,
  ],
  CategoryEnum.toysGadgets: [
    SubCategoryEnum.softToys,
    SubCategoryEnum.electronicToys,
    SubCategoryEnum.woodenToys,
    SubCategoryEnum.misc,
    SubCategoryEnum.otherToys,
  ],
  CategoryEnum.houseItems: [
    SubCategoryEnum.electronics,
    SubCategoryEnum.furniture,
    SubCategoryEnum.kitchen,
    SubCategoryEnum.electricals,
    SubCategoryEnum.eventFunction,
    SubCategoryEnum.clothing,
    SubCategoryEnum.otherHouseItems,
  ],
  CategoryEnum.others: [
    SubCategoryEnum.farmExtracts,
    SubCategoryEnum.localBrands,
    SubCategoryEnum.oilsAndGels,
    SubCategoryEnum.localProducts,
    SubCategoryEnum.energyDrinks,
    SubCategoryEnum.artisans,
    SubCategoryEnum.homeMade,
    SubCategoryEnum.otherOthers,
  ],
};

CategoryEnum? findCategoryForSubCategory(SubCategoryEnum subCategory) {
  for (var category in subCategoryListsForCategory.keys) {
    if (subCategoryListsForCategory[category]!.contains(subCategory)) {
      return category;
    }
  }
  return null; // Return null if subcategory is not found in any category
}

ParentEnum? findParentForCategory(CategoryEnum category) {
  for (var parent in categoryListForParentEnum.keys) {
    if (categoryListForParentEnum[parent]!.contains(category)) {
      return parent;
    }
  }
  return null; // Return null if subcategory is not found in any category
}

enum CategoryEnum {
  animals,
  birds,
  supplies,
  crops,
  vegetables,
  fruits,
  vehicles,
  equipments,
  tools,

  // land specific
  property,
  toysGadgets,
  houseItems,
  others,
}

var nameForCategoryEnum = {
  CategoryEnum.animals: "Animals",
  CategoryEnum.birds: "Birds",
  CategoryEnum.crops: "Grains/Pulses",
  CategoryEnum.vegetables: "Vegetables",
  CategoryEnum.fruits: "Fruits",
  CategoryEnum.vehicles: "Vehicles",
  CategoryEnum.tools: "Tools",
  CategoryEnum.equipments: "Equipments",
  CategoryEnum.supplies: "Supplies",
  CategoryEnum.property: "Property",
  CategoryEnum.toysGadgets: "Toys/Gadgets",
  CategoryEnum.houseItems: "House Items",
  CategoryEnum.others: "Others",
};

enum SubCategoryEnum {
  // animals
  cows,
  goats,
  buffaloes,
  sheep,
  bull,
  pig,

  // birds
  parrot,
  pigeon,
  sparrow,
  // chicken,
  duck,
  turkey,
  emu,

  //CROPS
  barley,
  bengalGram,
  castor,
  cotton,
  groundnut,
  jute,
  linseed,
  maize,
  mustard,
  pearlMillet,
  rabiMaize,
  soybean,
  sunflower,
  tobacco,
  turmeric,
  wheat,
  rice,
  jower,
  coffee,
  tea,
  pepper,
  coconut,
  arecanut,
  horsegram,
  ragi,
  chikpea,
  jaggery,
  tamrind,
  cashew,
  palmOil,
  greengram,
  arbi,
  ber,
  cowPea,
  cumin,
  kinnow,
  lentil,
  litchi,
  okra,
  pigenopea,
  ridgedGround,
  sorghum,
  sugarcane,
  tuberose,

  // VEGETABLES
  beans,
  beetroot,
  bittergourd,
  bottlegourd,
  brinjal,
  brocolli,
  cabbage,
  capsicum,
  carrot,
  cauliflower,
  chikPeas,
  chilli,
  clusterBean,
  coriander,
  cucumber,
  drumstick,
  frenchBeans,
  ginger,
  greenpeas,
  IvyGround,
  lemon,
  mentha,
  pointedGround,
  potato,
  pumpkin,
  raddish,
  snakeGround,
  spinach,
  spongeGround,
  tomato,
  sweetPotato,
  mashroom,
  ladyFinger,
  babycorn,
  milk,
  onions,
  garlic,

  // FRUITS
  amla,
  banana,
  gauva,
  grapes,
  jackfruit,
  mango,
  muskmelon,
  pineapple,
  sapota,
  watermelon,
  orange,
  strawberry,
  custardApple,
  papaya,
  pomegranate,
  apple,
  MarasebuPear,
  mosambi,
  muskMelon,
  tenderCoconut,
  dates,
  resins,
  fig,
  jamun,

  // FLOWERS
  rose,
  marigold,

  // MISCELLANEOUS
  egg,
  chicken,

  // ELECTRONICS
  mobile,
  laptop,
  tv,

  // JCB
  jcb,

  // EQUIPMENTS
  tractor,
  rotavator,
  cultivator,
  Backhoe,
  Billhook,
  Car,
  CombineHarvester,
  ElectricScooter,
  Equipment,
  Fan,
  GardeningTools,
  Loader,
  Plow,
  Scooter,
  Shredder,
  Tractor,

  // supplies
  soaps,
  petShelters,
  transporters,
  cleaner,
  honeyTools,
  hive,

  // property
  rentalProperty,
  farmStay,
  farmRental,
  buyNsale,
  farmLabour,
  greenhouse,
  otherProperty,

  // toysGadgets
  softToys,
  electronicToys,
  woodenToys,
  misc,
  otherToys,

  // houseItems
  electronics,
  furniture,
  kitchen,
  electricals,
  eventFunction,
  clothing,
  otherHouseItems,

  // others
  farmExtracts,
  localBrands,
  oilsAndGels,
  localProducts,
  energyDrinks,
  artisans,
  homeMade,
  otherOthers,
}

SubCategoryEnum? findSubCategoryEnumForName(String subCategory) {
  for (var subCategoryEnum in nameForSubCategoryEnum.keys) {
    if (nameForSubCategoryEnum[subCategoryEnum] == subCategory) {
      return subCategoryEnum;
    }
  }
  return null; // Return null if subcategory is not found in any category
}

var nameForSubCategoryEnum = {
  SubCategoryEnum.cows: "Cows",
  SubCategoryEnum.goats: "Goats",
  SubCategoryEnum.buffaloes: "Buffaloes",
  SubCategoryEnum.sheep: "Sheep",
  SubCategoryEnum.bull: "Bull",
  SubCategoryEnum.pig: "Pig",
  SubCategoryEnum.parrot: "Parrot",
  SubCategoryEnum.pigeon: "Pigeon",
  SubCategoryEnum.sparrow: "Sparrow",
  SubCategoryEnum.duck: "Duck",
  SubCategoryEnum.turkey: "Turkey",
  SubCategoryEnum.barley: "Barley",
  SubCategoryEnum.bengalGram: "Bengal Gram",
  SubCategoryEnum.castor: "Castor",
  SubCategoryEnum.cotton: "Cotton",
  SubCategoryEnum.groundnut: "Groundnut",
  SubCategoryEnum.jute: "Jute",
  SubCategoryEnum.linseed: "Linseed",
  SubCategoryEnum.maize: "Maize",
  SubCategoryEnum.mustard: "Mustard",
  SubCategoryEnum.pearlMillet: "Pearl Millet",
  SubCategoryEnum.rabiMaize: "Rabi Maize",
  SubCategoryEnum.soybean: "Soybean",
  SubCategoryEnum.sunflower: "Sunflower",
  SubCategoryEnum.tobacco: "Tobacco",
  SubCategoryEnum.turmeric: "Turmeric",
  SubCategoryEnum.wheat: "Wheat",
  SubCategoryEnum.rice: "Rice",
  SubCategoryEnum.jower: "Jower",
  SubCategoryEnum.coffee: "Coffee",
  SubCategoryEnum.tea: "Tea",
  SubCategoryEnum.pepper: "Pepper",
  SubCategoryEnum.coconut: "Coconut",
  SubCategoryEnum.arecanut: "Arecanut",
  SubCategoryEnum.horsegram: "Horsegram",
  SubCategoryEnum.ragi: "Ragi",
  SubCategoryEnum.chikpea: "Chikpea",
  SubCategoryEnum.jaggery: "Jaggery",
  SubCategoryEnum.tamrind: "Tamrind",
  SubCategoryEnum.cashew: "Cashew",
  SubCategoryEnum.palmOil: "Palm Oil",
  SubCategoryEnum.greengram: "Greengram",
  SubCategoryEnum.arbi: "Arbi",
  SubCategoryEnum.ber: "Ber",
  SubCategoryEnum.cowPea: "Cow Pea",
  SubCategoryEnum.cumin: "Cumin",
  SubCategoryEnum.kinnow: "Kinnow",
  SubCategoryEnum.lentil: "Lentil",
  SubCategoryEnum.litchi: "Litchi",
  SubCategoryEnum.okra: "Okra",
  SubCategoryEnum.pigenopea: "Pigenopea",
  SubCategoryEnum.ridgedGround: "Ridged Ground",
  SubCategoryEnum.sorghum: "Sorghum",
  SubCategoryEnum.sugarcane: "Sugarcane",
  SubCategoryEnum.tuberose: "Tuberose",
  SubCategoryEnum.beans: "Beans",
  SubCategoryEnum.beetroot: "Beetroot",
  SubCategoryEnum.bittergourd: "bittergourd",
  SubCategoryEnum.bottlegourd: "bottlegourd",
  SubCategoryEnum.brinjal: "Brinjal",
  SubCategoryEnum.brocolli: "Brocolli",
  SubCategoryEnum.cabbage: "Cabbage",
  SubCategoryEnum.capsicum: "Capsicum",
  SubCategoryEnum.carrot: "Carrot",
  SubCategoryEnum.cauliflower: "Cauliflower",
  SubCategoryEnum.chikPeas: "Chickpeas",
  SubCategoryEnum.chilli: "Chilli",
  SubCategoryEnum.clusterBean: "Cluster Bean",
  SubCategoryEnum.coriander: "Coriander",
  SubCategoryEnum.cucumber: "Cucumber",
  SubCategoryEnum.drumstick: "Drumstick",
  SubCategoryEnum.frenchBeans: "French Beans",
  SubCategoryEnum.ginger: "Ginger",
  SubCategoryEnum.greenpeas: "Green Peas",
  SubCategoryEnum.IvyGround: "Ivy Ground",
  SubCategoryEnum.lemon: "Lemon",
  SubCategoryEnum.mentha: "Mint",
  SubCategoryEnum.pointedGround: "Pointed Ground",
  SubCategoryEnum.potato: "Potato",
  SubCategoryEnum.pumpkin: "Pumpkin",
  SubCategoryEnum.raddish: "Radish",
  SubCategoryEnum.snakeGround: "Snake Ground",
  SubCategoryEnum.spinach: "Spinach",
  SubCategoryEnum.spongeGround: "Sponge Ground",
  SubCategoryEnum.tomato: "Tomato",
  SubCategoryEnum.sweetPotato: "Sweet Potato",
  SubCategoryEnum.mashroom: "Mushroom",
  SubCategoryEnum.ladyFinger: "Ladyfinger",
  SubCategoryEnum.babycorn: "Baby Corn",
  SubCategoryEnum.milk: "Milk",
  SubCategoryEnum.onions: "Onions",
  SubCategoryEnum.garlic: "Garlic",
  SubCategoryEnum.amla: "Amla",
  SubCategoryEnum.banana: "Banana",
  SubCategoryEnum.gauva: "Guava",
  SubCategoryEnum.grapes: "Grapes",
  SubCategoryEnum.jackfruit: "Jackfruit",
  SubCategoryEnum.mango: "Mango",
  SubCategoryEnum.muskmelon: "Muskmelon",
  SubCategoryEnum.pineapple: "Pineapple",
  SubCategoryEnum.sapota: "Sapota",
  SubCategoryEnum.watermelon: "Watermelon",
  SubCategoryEnum.orange: "Orange",
  SubCategoryEnum.strawberry: "Strawberry",
  SubCategoryEnum.custardApple: "Custard Apple",
  SubCategoryEnum.papaya: "Papaya",
  SubCategoryEnum.pomegranate: "Pomegranate",
  SubCategoryEnum.apple: "Apple",
  SubCategoryEnum.MarasebuPear: "Marasebu Pear",
  SubCategoryEnum.mosambi: "Mosambi",
  SubCategoryEnum.muskMelon: "Musk Melon",
  SubCategoryEnum.tenderCoconut: "Tender Coconut",
  SubCategoryEnum.dates: "Dates",
  SubCategoryEnum.resins: "Resins",
  SubCategoryEnum.fig: "Fig",
  SubCategoryEnum.jamun: "Jamun",
  SubCategoryEnum.rose: "Rose",
  SubCategoryEnum.marigold: "Marigold",
  SubCategoryEnum.egg: "Egg",
  SubCategoryEnum.chicken: "Chicken",
  SubCategoryEnum.mobile: "Mobile",
  SubCategoryEnum.laptop: "Laptop",
  SubCategoryEnum.tv: "TV",
  SubCategoryEnum.jcb: "JCB",
  SubCategoryEnum.tractor: "Tractor",
  SubCategoryEnum.rotavator: "Rotavator",
  SubCategoryEnum.cultivator: "Cultivator",
  SubCategoryEnum.Backhoe: "Backhoe",
  SubCategoryEnum.Billhook: "Billhook",
  SubCategoryEnum.Car: "Car",
  SubCategoryEnum.CombineHarvester: "Combine Harvester",
  SubCategoryEnum.ElectricScooter: "Electric Scooter",
  SubCategoryEnum.Equipment: "Equipment",
  SubCategoryEnum.Fan: "Fan",
  SubCategoryEnum.GardeningTools: "Gardening Tools",
  SubCategoryEnum.Loader: "Loader",
  SubCategoryEnum.Plow: "Plow",
  SubCategoryEnum.Scooter: "Scooter",
  SubCategoryEnum.Shredder: "Shredder",
  SubCategoryEnum.Tractor: "Tractor",
  SubCategoryEnum.emu: "Emu",
  SubCategoryEnum.soaps: 'Soaps',
  SubCategoryEnum.petShelters: 'Pet Shelters',
  SubCategoryEnum.transporters: 'Transporters',
  SubCategoryEnum.cleaner: 'Cleaner',
  SubCategoryEnum.honeyTools: 'Honey Tools',
  SubCategoryEnum.hive: 'Hive',

  // property
  SubCategoryEnum.rentalProperty: 'Rental Property',
  SubCategoryEnum.farmStay: 'Farm Stay',
  SubCategoryEnum.farmRental: 'Farm Rental',
  SubCategoryEnum.buyNsale: 'Buy & Sale',
  SubCategoryEnum.farmLabour: 'Farm Labour',
  SubCategoryEnum.greenhouse: 'Greenhouse',
  SubCategoryEnum.otherProperty: 'Others',

  SubCategoryEnum.softToys: 'Soft Toys',
  SubCategoryEnum.electronicToys: 'Electronic Toys',
  SubCategoryEnum.woodenToys: 'Wooden Toys',
  SubCategoryEnum.misc: 'Misc',
  SubCategoryEnum.otherToys: 'Others',

  // houseItems
  SubCategoryEnum.electronics: 'Electronics',
  SubCategoryEnum.furniture: 'Furniture',
  SubCategoryEnum.kitchen: 'Kitchen',
  SubCategoryEnum.electricals: 'Electricals',
  SubCategoryEnum.eventFunction: 'Event Function',
  SubCategoryEnum.clothing: 'Clothing',
  SubCategoryEnum.otherHouseItems: 'Others',

  // others
  SubCategoryEnum.farmExtracts: 'Farm Extracts',
  SubCategoryEnum.localBrands: 'Local Brands',
  SubCategoryEnum.oilsAndGels: 'Oils & Gels',
  SubCategoryEnum.localProducts: 'Local Products',
  SubCategoryEnum.energyDrinks: 'Energy Drinks',
  SubCategoryEnum.artisans: 'Artisans',
  SubCategoryEnum.homeMade: 'Home Made',
  SubCategoryEnum.otherOthers: 'Others',
};

var SubSubCategoryList = {
  SubCategoryEnum.cows: [
    'Cows',
    'Black Cows',
    'White Cows',
  ],
  SubCategoryEnum.goats: [
    'Goats',
    'Black Goats',
    'White Goats',
  ],
  SubCategoryEnum.buffaloes: [
    'Buffaloes',
    'Black Buffaloes',
    'White Buffaloes',
  ],
  SubCategoryEnum.sheep: [
    'Sheep',
    'Black Sheep',
    'White Sheep',
  ],
  SubCategoryEnum.bull: [
    'Bull',
  ],
  SubCategoryEnum.pig: [
    'Pig',
  ],
  SubCategoryEnum.parrot: [
    'Parrot',
    'Green Parrot',
  ],
  SubCategoryEnum.pigeon: [
    'Pigeon',
    'White Pigeon',
  ],
  SubCategoryEnum.sparrow: [
    'Sparrow',
    'White Sparrow',
  ],
  SubCategoryEnum.duck: [
    'Duck',
  ],
  SubCategoryEnum.turkey: [
    'Turkey',
  ],
  SubCategoryEnum.beans: [
    'Beans',
    'Green Beans',
    'Red Beans',
  ],
  SubCategoryEnum.beetroot: [
    'Beetroot',
    'Red Beetroot',
  ],
  SubCategoryEnum.bittergourd: [
    'bittergourd',
    'Green bittergourd',
  ],
  SubCategoryEnum.bottlegourd: [
    'bottlegourd',
  ],
  SubCategoryEnum.brinjal: [
    'Brinjal',
  ],
  SubCategoryEnum.brocolli: [
    'Brocolli',
  ],
  SubCategoryEnum.barley: [
    'Barley',
    'Barley Green',
  ],
  SubCategoryEnum.bengalGram: [
    'Bengal Gram',
    'Bengal Gram Green',
  ],
  SubCategoryEnum.castor: [
    'Castor',
    'Castor Green',
  ],
  SubCategoryEnum.banana: [
    'Banana',
    'Banana Green',
  ],
  SubCategoryEnum.gauva: [
    'Guava',
    'Guava Green',
  ],
  SubCategoryEnum.grapes: [
    'Grapes Black',
    'Grapes Green',
    'Grapes Red',
  ],
  SubCategoryEnum.jcb: [
    'On Rent',
    'Sell',
  ],
  SubCategoryEnum.tractor: [
    'On Rent',
    'Sell',
  ],
  SubCategoryEnum.rotavator: [
    'On Rent',
    'Sell',
  ],
  SubCategoryEnum.cultivator: [
    'On Rent',
    'Sell',
  ],
};
