enum ProductType {
  newProduct,
  secondHand,
  // onRent,
}

enum ProductQuantity { units, wkg, w500g, w250g, ltr, mtr, acre, feet }

var nameForProductQuantity = {
  ProductQuantity.units: "Units",
  ProductQuantity.wkg: "Kg",
  ProductQuantity.w500g: "500g",
  ProductQuantity.w250g: "250g",
  ProductQuantity.ltr: "Ltr",
  ProductQuantity.mtr: "Mtr",
  ProductQuantity.acre: "Acre",
  ProductQuantity.feet: "Feet",
};

enum ParentEnum {
  animal,
  food,
  machine,
  market,
}

var nameForParentEnum = {
  ParentEnum.animal: "Animals",
  ParentEnum.food: "Food",
  ParentEnum.machine: "Machine",
  ParentEnum.market: "Market",
};

var categoryListForParentEnum = {
  ParentEnum.animal: [
    CategoryEnum.animals,
    CategoryEnum.birds,
    CategoryEnum.supplies,
  ],
  ParentEnum.food: [
    CategoryEnum.vegetables,
    CategoryEnum.fruits,
    CategoryEnum.crops,
  ],
  ParentEnum.machine: [
    CategoryEnum.machines,
    CategoryEnum.attachments,
    CategoryEnum.sparesService,
  ],
  ParentEnum.market: [
    CategoryEnum.property,
    CategoryEnum.toysGadgets,
    CategoryEnum.houseItems,
    CategoryEnum.others,
  ],
};

var subCategoryListsForCategory = {
  CategoryEnum.animals: [
    SubCategoryEnum.cows,
    SubCategoryEnum.goats,
    SubCategoryEnum.buffaloes,
    SubCategoryEnum.sheep,
    SubCategoryEnum.pig,
    SubCategoryEnum.fish,
    SubCategoryEnum.dairyProducts,
    SubCategoryEnum.honey,
    SubCategoryEnum.pets,
    SubCategoryEnum.otherAnimals,
  ],
  CategoryEnum.birds: [
    SubCategoryEnum.chicken,
    SubCategoryEnum.chicks,
    SubCategoryEnum.eggs,
    SubCategoryEnum.duck,
    SubCategoryEnum.pigeon,
    SubCategoryEnum.turkey,
    SubCategoryEnum.otherBirds,
  ],
  CategoryEnum.supplies: [
    SubCategoryEnum.petFood,
    SubCategoryEnum.vetDoctor,
    SubCategoryEnum.petMedicine,
    SubCategoryEnum.petDailyCare,
    SubCategoryEnum.beeTools,
    SubCategoryEnum.hive,
    SubCategoryEnum.petToyTools,
    SubCategoryEnum.otherSupplies,
  ],
  CategoryEnum.vegetables: [
    SubCategoryEnum.beans,
    SubCategoryEnum.garlic,
    SubCategoryEnum.onion,
    SubCategoryEnum.beetroot,
    SubCategoryEnum.herekaiSorekaiAgalkai,
    SubCategoryEnum.okra,
    SubCategoryEnum.spinach,
    SubCategoryEnum.areca,
    SubCategoryEnum.brinjal,
    SubCategoryEnum.coconut,
    SubCategoryEnum.radish,
    SubCategoryEnum.rootVeggi,
    SubCategoryEnum.tamarind,
    SubCategoryEnum.cabbage,
    SubCategoryEnum.capsicum,
    SubCategoryEnum.drumstick,
    SubCategoryEnum.carrot,
    SubCategoryEnum.pumpkin,
    SubCategoryEnum.cauliflower,
    SubCategoryEnum.greeenPeas,
    SubCategoryEnum.mushroom,
    SubCategoryEnum.tomato,
    SubCategoryEnum.chili,
    SubCategoryEnum.cucumber,
    SubCategoryEnum.lemon,
    SubCategoryEnum.ginger,
    SubCategoryEnum.corn,
    SubCategoryEnum.otherVegetables,
  ],
  CategoryEnum.fruits: [
    SubCategoryEnum.banana,
    SubCategoryEnum.grape,
    SubCategoryEnum.mango,
    SubCategoryEnum.pomegranate,
    SubCategoryEnum.jackfruit,
    SubCategoryEnum.tenderCoconut,
    SubCategoryEnum.papaya,
    SubCategoryEnum.sapodilla,
    SubCategoryEnum.melon,
    SubCategoryEnum.orange,
    SubCategoryEnum.pineapple,
    SubCategoryEnum.watermelon,
    SubCategoryEnum.apple,
    SubCategoryEnum.custardApple,
    SubCategoryEnum.jamunFruit,
    SubCategoryEnum.cashew,
    SubCategoryEnum.Berrys,
    SubCategoryEnum.FruitJuice,
    SubCategoryEnum.otherFruits,
  ],
  CategoryEnum.crops: [
    SubCategoryEnum.RagiMillets,
    SubCategoryEnum.rice,
    SubCategoryEnum.Wheat,
    SubCategoryEnum.cereal,
    SubCategoryEnum.millets,
    SubCategoryEnum.oilSeeds,
    SubCategoryEnum.grams,
    SubCategoryEnum.Spices,
    SubCategoryEnum.beverageCrop,
    SubCategoryEnum.sweeteners,
    SubCategoryEnum.otherCrops,
  ],
  CategoryEnum.machines: [
    SubCategoryEnum.tiller,
    SubCategoryEnum.tractorBigMini,
    SubCategoryEnum.jcb,
    SubCategoryEnum.sprayerPlanter,
    SubCategoryEnum.combine_harvester,
    SubCategoryEnum.truckBigMini,
    SubCategoryEnum.waterTanker,
    SubCategoryEnum.trailerAttachments,
    SubCategoryEnum.taxi,
    SubCategoryEnum.logistics,
    SubCategoryEnum.otherMachines,
  ],
  CategoryEnum.attachments: [
    SubCategoryEnum.ArecaMachines,
    SubCategoryEnum.shredder,
    SubCategoryEnum.soilTesting,
    SubCategoryEnum.arecaPolisher,
    SubCategoryEnum.rotavator,
    SubCategoryEnum.cultivator,
    SubCategoryEnum.leveler,
    SubCategoryEnum.plow,
    SubCategoryEnum.AugerDrill,
    SubCategoryEnum.brushCutter,
    SubCategoryEnum.chainsaw,
    SubCategoryEnum.lawnmower,
    SubCategoryEnum.waterPump,
    SubCategoryEnum.welding,
    SubCategoryEnum.wheelbarrow,
    SubCategoryEnum.gardeningTools,
    SubCategoryEnum.maintenance,
    SubCategoryEnum.waterHose,
    SubCategoryEnum.otherAttachments,
  ],
  CategoryEnum.sparesService: [
    SubCategoryEnum.pipeDripSprinkler,
    SubCategoryEnum.starterBorewell,
    SubCategoryEnum.droneServices,
    SubCategoryEnum.warehouseGreenhouse,
    SubCategoryEnum.farmSecurity,
    SubCategoryEnum.smartIrrigation,
    SubCategoryEnum.smartFarm,
    SubCategoryEnum.solarPump,
    SubCategoryEnum.solarEnergy,
    SubCategoryEnum.cropDoctor,
    SubCategoryEnum.financeService,
    SubCategoryEnum.sensorsMeters,
    SubCategoryEnum.localManufacturing,
    SubCategoryEnum.service,
    SubCategoryEnum.otherServices,
  ],
  CategoryEnum.property: [
    SubCategoryEnum.rentalProperty,
    SubCategoryEnum.farmStay,
    SubCategoryEnum.farmRental,
    SubCategoryEnum.buyNsale,
    SubCategoryEnum.farmLabour,
    SubCategoryEnum.greenhouse,
    SubCategoryEnum.otherProperty,
  ],
  CategoryEnum.toysGadgets: [
    SubCategoryEnum.softToys,
    SubCategoryEnum.electronicToys,
    SubCategoryEnum.woodenToys,
    SubCategoryEnum.misc,
    SubCategoryEnum.otherToys,
  ],
  CategoryEnum.houseItems: [
    SubCategoryEnum.electronics,
    SubCategoryEnum.furniture,
    SubCategoryEnum.kitchen,
    SubCategoryEnum.electricals,
    SubCategoryEnum.eventFunction,
    SubCategoryEnum.clothing,
    SubCategoryEnum.otherHouseItems,
  ],
  CategoryEnum.others: [
    SubCategoryEnum.farmExtracts,
    SubCategoryEnum.localBrands,
    SubCategoryEnum.oilsAndGels,
    SubCategoryEnum.localProducts,
    SubCategoryEnum.energyDrinks,
    SubCategoryEnum.artisans,
    SubCategoryEnum.homeMade,
    SubCategoryEnum.otherOthers,
  ],
};

CategoryEnum? findCategoryForSubCategory(SubCategoryEnum subCategory) {
  for (var category in subCategoryListsForCategory.keys) {
    if (subCategoryListsForCategory[category]!.contains(subCategory)) {
      return category;
    }
  }
  return null; // Return null if subcategory is not found in any category
}

ParentEnum? findParentForCategory(CategoryEnum category) {
  for (var parent in categoryListForParentEnum.keys) {
    if (categoryListForParentEnum[parent]!.contains(category)) {
      return parent;
    }
  }
  return null; // Return null if subcategory is not found in any category
}

enum CategoryEnum {
  animals,
  birds,
  supplies,

  crops,
  vegetables,
  fruits,

  machines,
  attachments,
  sparesService,

  // market specific
  property,
  toysGadgets,
  houseItems,
  others,
}

var nameForCategoryEnum = {
  CategoryEnum.animals: "Animals",
  CategoryEnum.birds: "Birds",
  CategoryEnum.crops: "Grains/Pulses",
  CategoryEnum.vegetables: "Vegetables",
  CategoryEnum.fruits: "Fruits",
  CategoryEnum.machines: "Machines",
  CategoryEnum.attachments: "Attachments",
  CategoryEnum.sparesService: "Spares Service",
  CategoryEnum.supplies: "Supplies",
  CategoryEnum.property: "Property",
  CategoryEnum.toysGadgets: "Toys/Gadgets",
  CategoryEnum.houseItems: "House Items",
  CategoryEnum.others: "Others",
};

enum SubCategoryEnum {
  // animals
  cows,
  goats,
  buffaloes,
  sheep,
  pig,
  fish,
  dairyProducts,
  honey,
  pets,
  otherAnimals,

  // birds
  chicken,
  chicks,
  eggs,
  duck,
  pigeon,
  turkey,
  otherBirds,

  // supplies
  petFood,
  vetDoctor,
  petMedicine,
  petDailyCare,
  beeTools,
  hive,
  petToyTools,
  otherSupplies,

  // VEGETABLES
  beans,
  garlic,
  onion,
  beetroot,
  herekaiSorekaiAgalkai,
  okra,
  spinach,
  areca,
  brinjal,
  coconut,
  radish,
  rootVeggi,
  tamarind,
  cabbage,
  capsicum,
  drumstick,
  carrot,
  pumpkin,
  cauliflower,
  greeenPeas,
  mushroom,
  tomato,
  chili,
  cucumber,
  lemon,
  ginger,
  corn,
  otherVegetables,

  // fruits
  banana,
  grape,
  mango,
  pomegranate,
  jackfruit,
  tenderCoconut,
  papaya,
  sapodilla,
  melon,
  orange,
  pineapple,
  watermelon,
  apple,
  custardApple,
  jamunFruit,
  cashew,
  Berrys,
  FruitJuice,
  otherFruits,

  // crops
  RagiMillets,
  rice,
  Wheat,
  cereal,
  millets,
  oilSeeds,
  grams,
  Spices,
  beverageCrop,
  sweeteners,
  otherCrops,

  // machines
  tiller,
  tractorBigMini,
  jcb,
  sprayerPlanter,
  combine_harvester,
  truckBigMini,
  waterTanker,
  trailerAttachments,
  taxi,
  logistics,
  maintenance,
  otherMachines,

  // attachments
  ArecaMachines,
  shredder,
  soilTesting,
  arecaPolisher,
  rotavator,
  cultivator,
  leveler,
  plow,
  AugerDrill,
  brushCutter,
  chainsaw,
  lawnmower,
  waterPump,
  welding,
  wheelbarrow,
  gardeningTools,
  waterHose,
  otherAttachments,

  // spares and service
  pipeDripSprinkler,
  starterBorewell,
  droneServices,
  warehouseGreenhouse,
  farmSecurity,
  smartIrrigation,
  smartFarm,
  solarPump,
  solarEnergy,
  cropDoctor,
  financeService,
  sensorsMeters,
  localManufacturing,
  service,
  otherServices,

  // property
  rentalProperty,
  farmStay,
  farmRental,
  buyNsale,
  farmLabour,
  greenhouse,
  otherProperty,

  // toysGadgets
  softToys,
  electronicToys,
  woodenToys,
  misc,
  otherToys,

  // houseItems
  electronics,
  furniture,
  kitchen,
  electricals,
  eventFunction,
  clothing,
  otherHouseItems,

  // others
  farmExtracts,
  localBrands,
  oilsAndGels,
  localProducts,
  energyDrinks,
  artisans,
  homeMade,
  otherOthers,
}

SubCategoryEnum? findSubCategoryEnumForName(String subCategory) {
  for (var subCategoryEnum in nameForSubCategoryEnum.keys) {
    if (nameForSubCategoryEnum[subCategoryEnum] == subCategory) {
      return subCategoryEnum;
    }
  }
  return null; // Return null if subcategory is not found in any category
}

var nameForSubCategoryEnum = {
  // animals
  SubCategoryEnum.cows: "Cows",
  SubCategoryEnum.goats: "Goats",
  SubCategoryEnum.buffaloes: "Buffaloes",
  SubCategoryEnum.sheep: "Sheep",
  SubCategoryEnum.pig: "Pig",
  SubCategoryEnum.fish: "Fish",
  SubCategoryEnum.dairyProducts: "Dairy Products",
  SubCategoryEnum.honey: "Honey",
  SubCategoryEnum.pets: "Pets",
  SubCategoryEnum.otherAnimals: "Other Animals",

  // birds
  SubCategoryEnum.chicken: "Chicken",
  SubCategoryEnum.chicks: "Chicks",
  SubCategoryEnum.eggs: "Eggs",
  SubCategoryEnum.duck: "Duck",
  SubCategoryEnum.pigeon: "Pigeon",
  SubCategoryEnum.turkey: "Turkey",
  SubCategoryEnum.otherBirds: "Other Birds",

  // supplies
  SubCategoryEnum.petFood: "Pet Food",
  SubCategoryEnum.vetDoctor: "Vet Doctor",
  SubCategoryEnum.petMedicine: "Pet Medicine",
  SubCategoryEnum.petDailyCare: "Pet Daily Care",
  SubCategoryEnum.beeTools: "Bee Tools",
  SubCategoryEnum.hive: "Hive",
  SubCategoryEnum.petToyTools: "Pet Toy Tools",
  SubCategoryEnum.otherSupplies: "Other Supplies",

  // VEGETABLES
  SubCategoryEnum.beans: "Beans",
  SubCategoryEnum.garlic: "Garlic",
  SubCategoryEnum.onion: "Onion",
  SubCategoryEnum.beetroot: "Beetroot",
  SubCategoryEnum.herekaiSorekaiAgalkai: "Herekai Sorekai Agalkai",
  SubCategoryEnum.okra: "Okra",
  SubCategoryEnum.spinach: "Spinach",
  SubCategoryEnum.areca: "Areca",
  SubCategoryEnum.brinjal: "Brinjal",
  SubCategoryEnum.coconut: "Coconut",
  SubCategoryEnum.radish: "Radish",
  SubCategoryEnum.rootVeggi: "Root Veggi",
  SubCategoryEnum.tamarind: "Tamarind",
  SubCategoryEnum.cabbage: "Cabbage",
  SubCategoryEnum.capsicum: "Capsicum",
  SubCategoryEnum.drumstick: "Drumstick",
  SubCategoryEnum.carrot: "Carrot",
  SubCategoryEnum.pumpkin: "Pumpkin",
  SubCategoryEnum.cauliflower: "Cauliflower",
  SubCategoryEnum.greeenPeas: "Green Peas",
  SubCategoryEnum.mushroom: "Mushroom",
  SubCategoryEnum.tomato: "Tomato",
  SubCategoryEnum.chili: "Chili",
  SubCategoryEnum.cucumber: "Cucumber",
  SubCategoryEnum.lemon: "Lemon",
  SubCategoryEnum.ginger: "Ginger",
  SubCategoryEnum.corn: "Corn",
  SubCategoryEnum.otherVegetables: "Other Vegetables",

  // fruits
  SubCategoryEnum.banana: "Banana",
  SubCategoryEnum.grape: "Grape",
  SubCategoryEnum.mango: "Mango",
  SubCategoryEnum.pomegranate: "Pomegranate",
  SubCategoryEnum.jackfruit: "Jackfruit",
  SubCategoryEnum.tenderCoconut: "Tender Coconut",
  SubCategoryEnum.papaya: "Papaya",
  SubCategoryEnum.sapodilla: "Sapodilla",
  SubCategoryEnum.melon: "Melon",
  SubCategoryEnum.orange: "Orange",
  SubCategoryEnum.pineapple: "Pineapple",
  SubCategoryEnum.watermelon: "Watermelon",
  SubCategoryEnum.apple: "Apple",
  SubCategoryEnum.custardApple: "Custard Apple",
  SubCategoryEnum.jamunFruit: "Jamun Fruit",
  SubCategoryEnum.cashew: "Cashew",
  SubCategoryEnum.Berrys: "Berrys",
  SubCategoryEnum.FruitJuice: "Fruit Juice",
  SubCategoryEnum.otherFruits: "Other Fruits",

  // crops
  SubCategoryEnum.RagiMillets: "Ragi Millets",
  SubCategoryEnum.rice: "Rice",
  SubCategoryEnum.Wheat: "Wheat",
  SubCategoryEnum.cereal: "Cereal",
  SubCategoryEnum.millets: "Millets",
  SubCategoryEnum.oilSeeds: "Oil Seeds",
  SubCategoryEnum.grams: "Grams",
  SubCategoryEnum.Spices: "Spices",
  SubCategoryEnum.beverageCrop: "Beverage Crop",
  SubCategoryEnum.sweeteners: "Sweeteners",
  SubCategoryEnum.otherCrops: "Other Crops",

  // machines
  SubCategoryEnum.tiller: "Tiller",
  SubCategoryEnum.tractorBigMini: "Tractor Big Mini",
  SubCategoryEnum.jcb: "JCB",
  SubCategoryEnum.sprayerPlanter: "Sprayer Planter",
  SubCategoryEnum.combine_harvester: "Combine Harvester",
  SubCategoryEnum.truckBigMini: "Truck Big Mini",
  SubCategoryEnum.waterTanker: "Water Tanker",
  SubCategoryEnum.trailerAttachments: "Trailer Attachments",
  SubCategoryEnum.taxi: "Taxi",
  SubCategoryEnum.logistics: "Logistics",
  SubCategoryEnum.maintenance: "Maintenance",
  SubCategoryEnum.otherMachines: "Other Machines",

  // attachments
  SubCategoryEnum.ArecaMachines: "Areca Machines",
  SubCategoryEnum.shredder: "Shredder",
  SubCategoryEnum.soilTesting: "Soil Testing",
  SubCategoryEnum.arecaPolisher: "Areca Polisher",
  SubCategoryEnum.rotavator: "Rotavator",
  SubCategoryEnum.cultivator: "Cultivator",
  SubCategoryEnum.leveler: "Leveler",
  SubCategoryEnum.plow: "Plow",
  SubCategoryEnum.AugerDrill: "Auger Drill",
  SubCategoryEnum.brushCutter: "Brush Cutter",
  SubCategoryEnum.chainsaw: "Chainsaw",
  SubCategoryEnum.lawnmower: "Lawnmower",
  SubCategoryEnum.waterPump: "Water Pump",
  SubCategoryEnum.welding: "Welding",
  SubCategoryEnum.wheelbarrow: "Wheelbarrow",
  SubCategoryEnum.gardeningTools: "Gardening Tools",
  SubCategoryEnum.waterHose: "Water Hose",
  SubCategoryEnum.otherAttachments: "Other Attachments",

  // spares and service
  SubCategoryEnum.pipeDripSprinkler: "Pipe Drip Sprinkler",
  SubCategoryEnum.starterBorewell: "Starter Borewell",
  SubCategoryEnum.droneServices: "Drone Services",
  SubCategoryEnum.warehouseGreenhouse: "Warehouse Greenhouse",
  SubCategoryEnum.farmSecurity: "Farm Security",
  SubCategoryEnum.smartIrrigation: "Smart Irrigation",
  SubCategoryEnum.smartFarm: "Smart Farm",
  SubCategoryEnum.solarPump: "Solar Pump",
  SubCategoryEnum.solarEnergy: "Solar Energy",
  SubCategoryEnum.cropDoctor: "Crop Doctor",
  SubCategoryEnum.financeService: "Finance Service",
  SubCategoryEnum.sensorsMeters: "Sensors Meters",
  SubCategoryEnum.localManufacturing: "Local Manufacturing",
  SubCategoryEnum.service: "Service",
  SubCategoryEnum.otherServices: "Other Services",

  // property
  SubCategoryEnum.rentalProperty: 'Rental Property',
  SubCategoryEnum.farmStay: 'Farm Stay',
  SubCategoryEnum.farmRental: 'Farm Rental',
  SubCategoryEnum.buyNsale: 'Buy & Sale',
  SubCategoryEnum.farmLabour: 'Farm Labour',
  SubCategoryEnum.greenhouse: 'Greenhouse',
  SubCategoryEnum.otherProperty: 'Other Properties',
  SubCategoryEnum.softToys: 'Soft Toys',
  SubCategoryEnum.electronicToys: 'Electronic Toys',
  SubCategoryEnum.woodenToys: 'Wooden Toys',
  SubCategoryEnum.misc: 'Misc',
  SubCategoryEnum.otherToys: 'Other Toys',

  // houseItems
  SubCategoryEnum.electronics: 'Electronics',
  SubCategoryEnum.furniture: 'Furniture',
  SubCategoryEnum.kitchen: 'Kitchen',
  SubCategoryEnum.electricals: 'Electricals',
  SubCategoryEnum.eventFunction: 'Event Function',
  SubCategoryEnum.clothing: 'Clothing',
  SubCategoryEnum.otherHouseItems: 'Other House Items',

  // others
  SubCategoryEnum.farmExtracts: 'Farm Extracts',
  SubCategoryEnum.localBrands: 'Local Brands',
  SubCategoryEnum.oilsAndGels: 'Oils & Gels',
  SubCategoryEnum.localProducts: 'Local Products',
  SubCategoryEnum.energyDrinks: 'Energy Drinks',
  SubCategoryEnum.artisans: 'Artisans',
  SubCategoryEnum.homeMade: 'Home Made',
  SubCategoryEnum.otherOthers: 'Others',
};

var SubSubCategoryList = {
  SubCategoryEnum.cows: [
    'Amrit Mahal',
    'Deoni cattle',
    'Hallikar',
    'HF-Holstein Friesian Crossbred',
    'Javari Cattle',
    'Jersey Crossbred',
    'Khillari',
    'Malnad Giddas',
  ],
  SubCategoryEnum.goats: [
    'Barbari',
    'Sirohi',
    'Kenguri',
  ],
  SubCategoryEnum.buffaloes: [
    'Pandharpuri',
    'Dharwadi',
  ],
  SubCategoryEnum.sheep: [
    'Kenguri',
    'Bellary',
    'Mandya',
    'Hassan',
  ],
  SubCategoryEnum.pig: [
    'Desi breed',
    'Ankamali',
  ],
  SubCategoryEnum.dairyProducts: [
    'Milk',
    'Ghee',
    'Butter',
    'curd',
    'Cheese',
    'ice cream',
    'others',
  ],
  SubCategoryEnum.honey: [
    'Tuduve/serana',
    'European/ mellifera',
    'Family',
  ],
  SubCategoryEnum.pets: [
    'Dog',
    'Cat',
    'Fishes',
    'Others',
  ],
  SubCategoryEnum.chicken: [
    'Nati Koli',
    'Asil chicken',
    'Kadaknath',
    'VANARAJA',
    'Frizzle',
    'Giriraja',
    'Indian Giant',
  ],
  SubCategoryEnum.eggs: [
    'Nati egg',
    'Farm egg',
  ],
  SubCategoryEnum.chicks: [
    'Male',
    'Female',
  ],

  // supplies
  SubCategoryEnum.petFood: [
    'Animals',
    'Birds',
    'Dogs',
    'Cats',
  ],
  SubCategoryEnum.petDailyCare: [
    'Cleaning',
    'Grooming',
  ],
  SubCategoryEnum.beeTools: [
    'Safety wearable',
    'Stand',
    'Extractor',
    'Wax',
  ],
  SubCategoryEnum.hive: [
    'Wood',
    'Family',
    'Bottles',
  ],
  SubCategoryEnum.beans: [
    'Cluster beans / gorikai',
    'Double beans',
    'Rajma beans',
    'Round beans',
    'Soya',
    'Togari',
  ],
  SubCategoryEnum.onion: [
    'Bangalore Rose Onions',
    'White',
    'Lasalgaon Onions',
  ],
  SubCategoryEnum.herekaiSorekaiAgalkai: [
    'Ash Gourd',
    'Bitter Gourd',
    'Bitter Gourd - Forest',
    'Bottle Gourd',
    'Ridge Gourd',
    'Snake Gourd',
    'Sponge Gourd',
  ],
  SubCategoryEnum.spinach: [
    'Amaranthus',
    'Betel Leaf',
    'Coriander Leaves',
    'Curry Leaves',
    'Dill Leaves',
    'Drumstick Leaves',
    'Gongura Leaves',
    'Methi',
    'Mint Leaves',
    'Tulsi Leaves',
  ],
  SubCategoryEnum.brinjal: [
    'Green Round',
    'Green Round',
    'Green, Long',
    'Purple, Long',
    'Bharta,',
    'Varikatri,',
    'Nagpur,',
  ],
  SubCategoryEnum.coconut: [
    'Tender coconut',
    'Elder coconut',
    'Dry coconut',
  ],
  SubCategoryEnum.rootVeggi: [
    'Potato',
    'Genasu / Sweet Potato',
    'Maragenasu / Tapioca',
    'Ginger',
    'Turnip',
    'Kachalu',
    'Turmeric',
    'Survarnagedde / Yam',
  ],
  SubCategoryEnum.drumstick: [
    'Drumstick',
    'Drumstick leaves',
  ],
  SubCategoryEnum.pumpkin: [
    'Ash Gourd/Boodu kumbalakai',
  ],
  SubCategoryEnum.greeenPeas: [
    'Green peas',
    'Dry peas',
  ],
  SubCategoryEnum.chili: [
    'Green',
    'Byadagi',
    'Guntur',
    'Bonda chilli',
  ],
  SubCategoryEnum.cucumber: [
    'Cucumber',
    'Gerkin',
    'Mangalore Cucumber',
    'White Cucumber',
  ],
  SubCategoryEnum.lemon: [
    'Lemon',
    'Grapefruit',
    'Sweet Lime',
    'Pomelo / Chakota',
    'Yallikai / Bitter Orange',
    'Grape Fruit',
    'Carambola/Star Fruit',
  ],
  SubCategoryEnum.corn: [
    'Sweet Corn',
    'Baby Corn',
    'Corn',
  ],
  SubCategoryEnum.banana: [
    'Elakki',
    'Pachabale',
    'Nendra Bale',
    'Rasa Baale',
  ],
  SubCategoryEnum.grape: [
    'Green Seedless',
    'Black Seedless',
    'Green',
    'Black Grape Juice',
    'Dry Grapes',
  ],
  SubCategoryEnum.mango: [
    'Alphonso',
    'Badami',
    'baganpalli',
    'Himsagar',
    'Kesar',
    'Malgova',
    'Neelam',
    'Raspuri',
    'Ratnagiri',
    'Sindhura',
    'Totapuri',
  ],
  SubCategoryEnum.tenderCoconut: [
    'Red',
    'Green',
  ],
  SubCategoryEnum.melon: [
    'Muskmelon',
    'Cantaloupe',
  ],
  SubCategoryEnum.orange: [
    'Coorg Orange',
    'Sweet Lime',
    'Mosambi',
    'Nagpur Orange',
  ],
  SubCategoryEnum.pineapple: [
    'Queen or common queen',
    'Kew',
    'Mauritius',
    'Jaldhup',
  ],
  SubCategoryEnum.watermelon: [
    'Watermelon Naati',
    'Watermelon Hybrid',
  ],
  SubCategoryEnum.custardApple: [
    'Nati',
    'Hybrid',
  ],
  SubCategoryEnum.jamunFruit: [
    'Nati',
    'Hybrid',
  ],
  SubCategoryEnum.cashew: [
    'Full',
    'Pieces',
  ],
  SubCategoryEnum.Berrys: [
    'Mulberry',
    'Gooseberry',
    'Strawberry',
  ],
  SubCategoryEnum.otherFruits: [
    'Fig',
    'Dragon Fruit',
  ],
  SubCategoryEnum.millets: [
    'Bajra / Millet',
    'Harka / Kodo Millet',
    'Jola / Sorghum',
    'korale / Brown Top Millet',
    'Navane / Foxtail Millet',
    'ragi / Finger Millet',
    'Saame / Little Millet',
    'Sajje / Pearl Millet',
  ],
  SubCategoryEnum.rice: [
    'Basmathi',
    'Hamsa',
    'IR - 20',
    'Jaya',
    'Kusulakki',
    'Mangala',
    'Rajmudi',
    'Red Rice',
    'Sona Masoori',
  ],
  SubCategoryEnum.cereal: [
    'Barley',
    'Maize',
    'Oat',
    'Sorghum',
  ],
  SubCategoryEnum.oilSeeds: [
    'Castor Seeds',
    'Groundnut',
    'Mustard',
    'Niger Seed',
    'Palm',
    'Safflower',
    'Sesame',
    'Soybean',
    'Sunflower',
  ],
  SubCategoryEnum.grams: [
    'Toor Dal',
    'Green Gram',
    'Black gram',
    'Bengal gram',
    'Cow Peas',
    'Horse gram',
  ],
  SubCategoryEnum.Spices: [
    'Black Pepper',
    'Cardamom',
    'Cinnamon',
    'Cloves',
    'Cumin Seeds',
    'Asafoetida',
    'Fenugreek',
    'Mustard',
    'Poppy Seeds',
    'Flax Seeds',
  ],
  SubCategoryEnum.sweeteners: [
    'Jaggery',
    'Pickle',
    'Happala',
    'Sandige',
  ],

  SubCategoryEnum.eventFunction: [
    'Event',
    'Function',
    'Parties',
    'Festive Events',
  ],
  SubCategoryEnum.clothing: [
    'Kids',
    'Ladies',
  ],
  SubCategoryEnum.furniture: [
    'Carpenter',
    'Furniture',
  ],
  SubCategoryEnum.kitchen: [
    'Utensiils',
    'Pottery',
  ],

  SubCategoryEnum.electricals: [
    'Swithches',
    'Lights',
    'Wirings',
    'Others',
  ],
  SubCategoryEnum.softToys: [
    'Teddy Bears',
    'Dolls',
  ],
  SubCategoryEnum.electronicToys: [
    'Remote Control Toys',
    'Indoor Games',
    'Outdoor Games',
  ],
  SubCategoryEnum.woodenToys: [
    'Indoor games',
    'Outdoor games',
  ],
  SubCategoryEnum.homeMade: [
    'Pickles',
    'Pappad',
    'Sweets Biscuits',
    'Cakes Chocolates',
  ],

  // machines
  SubCategoryEnum.tiller: [
    'Garden Tiller',
    'Rear Action Tiller',
    'Front Action Tiller',
    'Vertical Action Tiller',
  ],
  SubCategoryEnum.tractorBigMini: [
    'Big > 40HP',
    'Medium 30-40 HP',
    'Small 15-30 HP',
    'Mini <15HP',
    'All wheel drive',
    'Electric',
  ],
  SubCategoryEnum.sprayerPlanter: [
    'Baler',
    'Rake',
    'Sugarcane Loader',
  ],
  SubCategoryEnum.combine_harvester: [
    'Harvester',
    'Baler',
    'Forage Mover',
    'Sugarcane Loader',
  ],
  SubCategoryEnum.truckBigMini: [
    'Goods Auto',
    'Tata Ace',
    'Dost',
    'Canter',
    'Truck',
  ],
  SubCategoryEnum.waterTanker: [
    'Water Tanker',
    'Milk Tanker',
  ],
  SubCategoryEnum.trailerAttachments: [
    'Trailer',
    'Boom Sprayer',
    'Fertilizer Spreader',
  ],
  SubCategoryEnum.taxi: [
    'Bike',
    'Auto',
    'Car',
    'Van',
    'Tempo Traveller',
    'Bus',
  ],
  SubCategoryEnum.maintenance: [
    'Bike',
    'Petrol Vehicle',
    'Diesel Vehicle',
  ],

  SubCategoryEnum.ArecaMachines: [
    'Trailer Mounted De-Husker',
    'Fixed De-Husker',
    'Electric / Diesel ',
  ],
  SubCategoryEnum.shredder: [
    'Small',
    'Medium',
    'Large',
  ],
  SubCategoryEnum.arecaPolisher: [
    'Drum Type',
    'Cylindrical',
    'Others',
  ],
  SubCategoryEnum.rotavator: [
    'Small',
    'Medium',
    'Large',
  ],
  SubCategoryEnum.AugerDrill: [
    'Small',
    'Medium',
    'Large',
  ],
  SubCategoryEnum.brushCutter: [
    'Small',
    'Medium',
    'Large',
  ],
  SubCategoryEnum.chainsaw: [
    'Small',
    'Medium',
    'Large',
  ],
  SubCategoryEnum.lawnmower: [
    'Small',
    'Medium',
    'Large',
  ],
};
